import{createUpgradeDefinition}from'./UpgradeDefinition.js';
const level=(description,data={})=>({description,...data});
const defs=[
 createUpgradeDefinition({id:'split-lens',name:'Split Lens',category:'Weapon',initiallyUnlocked:true,tags:['projectile','multishot'],levels:[level('1 side projectile at 8°; all projectiles deal 72% base damage',{count:2,angles:[0,8],scalar:.72,fragmentGuardMs:80}),level('2 side projectiles at ±9°; all three deal 62% base damage',{count:3,angles:[-9,0,9],scalar:.62,fragmentGuardMs:80})]}),
 createUpgradeDefinition({id:'piercing-signal',name:'Piercing Signal',category:'Weapon',initiallyUnlocked:true,tags:['projectile','pierce'],levels:[1,2,3].map(v=>level(`+${v} enemy pierce; ×0.82 after each pierce; 45% floor`,{pierce:v,decay:.82,floor:.45}))}),
 createUpgradeDefinition({id:'arc-relay',name:'Arc Relay',category:'Weapon',initiallyUnlocked:true,tags:['chain','hit-trigger'],levels:[level('Every 6th hit chains to 1 target at 45%',{hitCadence:6,targetCount:1,scalar:.45,range:220}),level('Every 6th hit chains to 2 targets at 42% each',{hitCadence:6,targetCount:2,scalar:.42,range:220}),level('Every 6th hit chains to 3 targets at 40% each',{hitCadence:6,targetCount:3,scalar:.40,range:220})]}),
 createUpgradeDefinition({id:'fracture-round',name:'Fracture Round',category:'Weapon',initiallyUnlocked:true,tags:['critical','fragment'],levels:[level('Critical hits release 2 fragments at 35%',{count:2,scalar:.35,speedScalar:.70,lifetimeMs:500}),level('Critical hits release 3 fragments at 33%',{count:3,scalar:.33,speedScalar:.70,lifetimeMs:500}),level('Critical hits release 4 fragments at 30%',{count:4,scalar:.30,speedScalar:.70,lifetimeMs:500})]}),
 createUpgradeDefinition({id:'compression-coil',name:'Compression Coil',category:'Weapon',initiallyUnlocked:true,tags:['continuous-fire','stat'],levels:[level('+12% speed and +8% damage at full charge',{speed:1.12,damage:1.08,chargeMs:1200,decayMs:350,dashRetention:.5}),level('+18% speed and +12% damage at full charge',{speed:1.18,damage:1.12,chargeMs:1200,decayMs:350,dashRetention:.5}),level('+24% speed and +16% damage at full charge',{speed:1.24,damage:1.16,chargeMs:1200,decayMs:350,dashRetention:.5})]}),
 createUpgradeDefinition({id:'ricochet-matrix',name:'Ricochet Matrix',category:'Weapon',initiallyUnlocked:true,tags:['projectile','wall'],levels:[level('1 wall bounce; ×0.82 post-bounce damage',{bounces:1,decay:.82,sameTargetGuardMs:120}),level('2 wall bounces; each ×0.82 current damage',{bounces:2,decay:.82,sameTargetGuardMs:120})]}),
 createUpgradeDefinition({id:'extended-memory',name:'Extended Memory',category:'Echo',initiallyUnlocked:true,tags:['echo','recording'],levels:[1,2,3].map(v=>level(`+${(v*.6).toFixed(1)}s replay; +${(v*.25).toFixed(2)}s cooldown`,{durationBonusMs:v*600,maximumDurationMs:5300,cooldownBonusMs:v*250}))}),
 createUpgradeDefinition({id:'twin-recall',name:'Twin Recall',category:'Echo',initiallyUnlocked:false,tags:['echo','secondary'],maxLevel:1,levels:[level('A second Echo starts 650ms later at 75% primary scalar',{delayMs:650,secondaryScalar:.75,cooldownBonusMs:1000,activeCap:2})]}),
 createUpgradeDefinition({id:'resonant-damage',name:'Resonant Damage',category:'Echo',initiallyUnlocked:true,tags:['echo','crossfire'],levels:[.12,.18,.24].map(v=>level(`Crossfire deals +${Math.round(v*100)}% damage`,{bonus:v,windowMs:1000,targetCooldownMs:650}))}),
 createUpgradeDefinition({id:'phantom-shield',name:'Phantom Shield',category:'Echo',initiallyUnlocked:true,tags:['echo','interception'],levels:[1,3,5].map(v=>level(`Each Echo destroys ${v} hostile projectile${v===1?'':'s'}`,{capacity:v}))}),
 createUpgradeDefinition({id:'stable-projection',name:'Stable Projection',category:'Echo',initiallyUnlocked:true,tags:['echo','stat'],levels:[1,2,3].map(v=>level(`Echo scalar ${(0.55+v*.10).toFixed(2)}`,{scalar:.55+v*.10,cap:.90}))}),
 createUpgradeDefinition({id:'memory-burst',name:'Memory Burst',category:'Echo',initiallyUnlocked:false,tags:['echo','expiration','area'],levels:[level('Echo expiration bursts for 24 damage in 90px',{radius:90,damage:24}),level('Echo expiration bursts for 36 damage in 110px',{radius:110,damage:36}),level('Echo expiration bursts for 48 damage in 130px',{radius:130,damage:48})]}),
 createUpgradeDefinition({id:'dash-wake',name:'Dash Wake',category:'Mobility',initiallyUnlocked:true,tags:['dash','area'],levels:[18,27,36].map(v=>level(`Dash leaves a 450ms wake dealing ${v}`,{damage:v,lifetimeMs:450,width:28,echoScalar:.55}))}),
 createUpgradeDefinition({id:'phase-recovery',name:'Phase Recovery',category:'Mobility',initiallyUnlocked:true,tags:['near-miss','echo-cooldown'],levels:[120,180,240].map(v=>level(`Near misses reduce Echo cooldown by ${v}ms`,{radiusBonus:28,reductionMs:v,internalCooldownMs:500}))}),
 createUpgradeDefinition({id:'kinetic-charge',name:'Kinetic Charge',category:'Mobility',initiallyUnlocked:true,tags:['movement','fire-rate'],levels:[.08,.13,.18].map(v=>level(`Sustained movement grants +${Math.round(v*100)}% fire rate`,{bonus:v,threshold:.70,chargeMs:1500,decayMs:600}))}),
 createUpgradeDefinition({id:'vector-reversal',name:'Vector Reversal',category:'Mobility',initiallyUnlocked:false,tags:['dash'],levels:[level('Opposite dash within 450ms at 70% distance',{windowMs:450,distanceScalar:.70,minimumAngleDegrees:120}),level('Opposite dash within 600ms at 85% distance',{windowMs:600,distanceScalar:.85,minimumAngleDegrees:120})]}),
 createUpgradeDefinition({id:'slipstream',name:'Slipstream',category:'Mobility',initiallyUnlocked:true,tags:['echo','movement'],levels:[.12,.18,.24].map(v=>level(`Passing near an Echo grants +${Math.round(v*100)}% speed for 1.2s`,{bonus:v,distance:46,durationMs:1200,perEchoCooldownMs:1500,movementCap:440}))}),
 createUpgradeDefinition({id:'afterburn',name:'Afterburn',category:'Mobility',initiallyUnlocked:false,tags:['dash','projectile'],levels:[.35,.55,.75].map(v=>level(`First shot within 300ms after dash deals +${Math.round(v*100)}% damage`,{bonus:v,windowMs:300,sideShotScalar:.5}))}),
 createUpgradeDefinition({id:'emergency-repair',name:'Emergency Repair',category:'Defense',initiallyUnlocked:true,tags:['healing','segment'],levels:[6,10,14].map(v=>level(`Heal ${v} after a combat chamber`,{heal:v}))}),
 createUpgradeDefinition({id:'reactive-shell',name:'Reactive Shell',category:'Defense',initiallyUnlocked:true,tags:['damage-reduction'],levels:[.15,.22,.30].map(v=>level(`${Math.round(v*100)}% damage reduction for 2.0s after a hit`,{reduction:v,durationMs:2000}))}),
 createUpgradeDefinition({id:'null-absorption',name:'Null Absorption',category:'Defense',initiallyUnlocked:false,tags:['projectile-destruction','echo-cooldown','rng'],levels:[level('15% projectile-destruction chance: -150ms Echo cooldown',{chance:.15,reductionMs:150,internalCooldownMs:180}),level('22% chance: -180ms Echo cooldown',{chance:.22,reductionMs:180,internalCooldownMs:180}),level('30% chance: -220ms Echo cooldown',{chance:.30,reductionMs:220,internalCooldownMs:180})]}),
 createUpgradeDefinition({id:'last-frame',name:'Last Frame',category:'Defense',initiallyUnlocked:true,tags:['lethal-prevention'],maxLevel:1,levels:[level('Once per combat chamber, lethal damage leaves 1 HP and grants 1.2s invulnerability',{invulnerabilityMs:1200})]}),
 createUpgradeDefinition({id:'regenerative-circuit',name:'Regenerative Circuit',category:'Defense',initiallyUnlocked:true,tags:['healing','time'],levels:[level('After 8s: 1 HP / 1.6s, chamber cap 8',{delayMs:8000,tickMs:1600,cap:8}),level('After 7s: 1 HP / 1.4s, chamber cap 12',{delayMs:7000,tickMs:1400,cap:12}),level('After 6s: 1 HP / 1.2s, chamber cap 16',{delayMs:6000,tickMs:1200,cap:16})]}),
 createUpgradeDefinition({id:'deflection-pulse',name:'Deflection Pulse',category:'Defense',initiallyUnlocked:false,tags:['dash','displacement','playtest-trigger'],levels:[level('Dash-start pulse: 110px radius, 55px push',{radius:110,push:55,eliteScalar:.5}),level('Dash-start pulse: 135px radius, 75px push',{radius:135,push:75,eliteScalar:.5}),level('Dash-start pulse: 160px radius, 95px push',{radius:160,push:95,eliteScalar:.5})]}),
];
export const UPGRADE_CATALOG=Object.freeze(Object.fromEntries(defs.map(x=>[x.id,x])));
export const UPGRADE_DEFINITIONS=Object.freeze(defs);
export const UPGRADE_IDS=Object.freeze(defs.map(x=>x.id));
export const INITIAL_UNLOCKED_UPGRADE_IDS=Object.freeze(defs.filter(x=>x.initiallyUnlocked).map(x=>x.id));
export const LOCKED_UPGRADE_IDS=Object.freeze(defs.filter(x=>!x.initiallyUnlocked).map(x=>x.id));
export function getUpgrade(id){return UPGRADE_CATALOG[id]??null;}
