import test from 'node:test';
import assert from 'node:assert/strict';
import { SeededRandom } from '../src/utils/SeededRandom.js';
import { BOSS_SECTOR_PATTERNS, BOSS_SECTOR_RULES } from '../src/data/bossSectorDefinitions.js';
import { validateSectorPattern, createSectorDeletionPlan } from '../src/boss/attacks/SectorDeletionAttack.js';
import { createRearPanelPlan } from '../src/boss/attacks/RearPanelExposureAttack.js';
import { convertHostileEchoReplay } from '../src/hostile-echo/HostileEchoEventConverter.js';
import { HostileEchoSpawnValidator } from '../src/hostile-echo/HostileEchoSpawnValidator.js';

for (const pattern of BOSS_SECTOR_PATTERNS) test(`sector pattern ${pattern.id} preserves safe connected space`, () => { const result=validateSectorPattern(pattern); assert.equal(result.valid,true); assert.ok(result.safeRatio>=BOSS_SECTOR_RULES.minimumSafeRatio); assert.equal(result.connected,true); assert.ok(result.minimumRouteWidth>=90); });
for (let seed=1;seed<=8;seed+=1) test(`sector selection ${seed} is bounded and non-overlapping data`, () => { const plan=createSectorDeletionPlan({rng:new SeededRandom(seed),previousPatternId:seed%2?null:'opposite-wedges'}); assert.equal(plan.validation.valid,true); assert.ok(plan.disabledMs>=2500&&plan.disabledMs<=3500); assert.equal(plan.warningMs,1000); assert.equal(plan.damage,16); assert.equal(plan.tickMs,700); });
for (let seed=1;seed<=6;seed+=1) test(`rear-panel selection ${seed} chooses far-side readable targets outside disabled panels`, () => { const disabled=seed%2?['north']:['east']; const plan=createRearPanelPlan({rng:new SeededRandom(seed),playerAngle:seed*Math.PI/4,disabledPanelIds:disabled}); assert.ok(plan.panelIds.length>=1&&plan.panelIds.length<=2); assert.ok(plan.panelIds.every(id=>!disabled.includes(id))); assert.ok(plan.durationMs>=3500&&plan.durationMs<=4500); assert.ok(plan.targetSize>=40); });
for (let seed=1;seed<=3;seed+=1) test(`hostile replay conversion ${seed} is immutable, finite, curated, and upgrade-free`, () => { const descriptor={snapshots:[{timestampMs:0,x:200,y:300,aimX:1,aimY:0},{timestampMs:3800,x:400,y:500,aimX:0,aimY:1}],fireEvents:Array.from({length:30},(_,i)=>({timestampMs:i*100,aimX:1,aimY:0}))}; const replay=convertHostileEchoReplay({descriptor,rng:new SeededRandom(seed),offset:{x:100,y:-50},phase:'IMITATE'}); assert.equal(Object.isFrozen(replay),true); assert.equal(replay.inheritedUpgradeIds.length,0); assert.ok(replay.fireEvents.length<=19); assert.ok(replay.snapshots.every(s=>Number.isFinite(s.x)&&Number.isFinite(s.y))); });
for (let seed=1;seed<=3;seed+=1) test(`hostile spawn validation ${seed} rejects player overlap and finds a bounded safe candidate`, () => { const validator=new HostileEchoSpawnValidator(); const context={bounds:{left:100,right:1500,top:90,bottom:810},player:{x:800,y:450},boss:{x:800,y:450,radius:150},solids:[],hostileEchoes:[]}; assert.equal(validator.validate({x:800,y:450},context).valid,false); const chosen=validator.choose({rng:new SeededRandom(seed),origin:{x:300,y:300},context,fallbackSockets:[{x:200,y:200},{x:1400,y:700}]}); assert.equal(chosen.accepted,true); assert.ok(Math.hypot(chosen.point.x-800,chosen.point.y-450)>=260); });
