import test from 'node:test';
import assert from 'node:assert/strict';
import { SaveManager } from '../src/systems/SaveManager.js';
import { createMemoryStorage } from '../src/utils/storage.js';
import { RunFinalizationService } from '../src/systems/RunFinalizationService.js';
import { ScoreManager } from '../src/scoring/ScoreManager.js';
import { createDefaultSaveData } from '../src/state/defaultSaveData.js';

function makeRun(index=0,difficultyId='standard'){
 const scoreManager=new ScoreManager({runId:`run-${index}`,difficultyId});scoreManager.recordEnemyDefeat({enemyType:'drifter',enemyId:`enemy-${index}`,source:'player'},{simulationMs:100,segmentId:'combat-1',segmentType:'COMBAT'});scoreManager.recordSegmentClear('combat-1',{simulationMs:1000,segmentId:'combat-1',segmentType:'COMBAT'});
 return {runId:`run-${index}`,seed:index,difficultyId,scoreManager,segmentDurations:{'combat-1':75000},statistics:{combat:{damageTaken:0}},selectedUpgradeHistory:[],arenaSequence:[],eliteModifiersDefeated:[],segmentHealthStart:{'combat-1':100},segmentHealthEnd:{'combat-1':100},bossStarted:false,combatElapsedMs:75000,playerHealth:100};
}
function result(result='defeat'){return {result,durationMs:75000,statistics:{damageTaken:0,playerDamageDealt:100,echoDamageDealt:0,playerShotsFired:50,playerProjectileHits:25,playerKills:1,echoKills:0,driftersDefeated:1,playerDashes:3,crossfireEvents:0},segmentDurations:{'combat-1':75000},selectedUpgradeHistory:[],eliteModifiersDefeated:[],arenaSequence:[],finalPlayerHealth:100};}
for(let index=0;index<20;index++)test(`Run finalization persists exactly once ${index}`,()=>{const saveManager=new SaveManager({storage:createMemoryStorage(),throttleMs:0});saveManager.load();const service=new RunFinalizationService({saveManager});const run=makeRun(index);const first=service.finalize({run,result:result()});const second=service.finalize({run,result:result()});assert.equal(first.committed,true);assert.equal(second.reason,'already-finalized');const save=saveManager.getSnapshot();assert.equal(save.statistics.aggregateCounters.runsCompleted,1);assert.equal(save.records.recentRuns.length,1);});
for(let index=0;index<10;index++)test(`Debug finalization never persists ${index}`,()=>{const saveManager=new SaveManager({storage:createMemoryStorage(),throttleMs:0});saveManager.load();const service=new RunFinalizationService({saveManager});const before=saveManager.exportJson();const finalized=service.finalize({run:makeRun(index),result:result(),debug:true});assert.equal(finalized.persisted,false);assert.equal(saveManager.exportJson(),before);});
for(let index=0;index<10;index++)test(`Standard victory unlocks Overclocked once ${index}`,()=>{const saveManager=new SaveManager({storage:createMemoryStorage(),throttleMs:0});saveManager.load();const service=new RunFinalizationService({saveManager});const run=makeRun(index,'standard');run.bossStarted=true;run.scoreManager.recordSegmentClear('boss',{simulationMs:2000,segmentId:'boss',segmentType:'BOSS'});const r={...result('victory'),bossImplemented:true,bossDurationMs:220000,bossPhase:'DELETE',bossTelemetry:{}};const finalized=service.finalize({run,result:r});assert.ok(finalized.result.appliedUnlockIds.includes('unlock-overclocked'));assert.ok(saveManager.getSnapshot().progression.unlockedDifficultyIds.includes('overclocked'));});
for(let index=0;index<10;index++)test(`Relaxed victory does not unlock Overclocked ${index}`,()=>{const saveManager=new SaveManager({storage:createMemoryStorage(),throttleMs:0});saveManager.load();const service=new RunFinalizationService({saveManager});const run=makeRun(index,'relaxed');run.bossStarted=true;const r={...result('victory'),bossImplemented:true,bossDurationMs:220000,bossPhase:'DELETE',bossTelemetry:{}};service.finalize({run,result:r});assert.ok(!saveManager.getSnapshot().progression.unlockedDifficultyIds.includes('overclocked'));});
for(let index=0;index<10;index++)test(`Recent run history remains capped after finalizations ${index}`,()=>{const data=createDefaultSaveData();data.records.recentRuns=Array.from({length:50},(_,i)=>({runId:`old-${i}`,result:'defeat',seed:i,difficultyId:'standard',finalScore:i}));const storage=createMemoryStorage();storage.setItem('echoframe.save.v1',JSON.stringify(data));const saveManager=new SaveManager({storage,throttleMs:0});saveManager.load();const service=new RunFinalizationService({saveManager});service.finalize({run:makeRun(index),result:result()});assert.equal(saveManager.getSnapshot().records.recentRuns.length,50);});
