import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (relative) => readFileSync(path.join(ROOT, relative), 'utf8');
const json = (relative) => JSON.parse(read(relative));

const contracts = [
  ['Phase 11 · package remains release candidate before Firefox certification', () => assert.equal(json('package.json').version, '1.0.0-release-candidate')],
  ['Phase 11 · package lock matches package identity', () => assert.equal(json('package-lock.json').version, json('package.json').version)],
  ['Phase 11 · runtime version remains release candidate before certification', () => assert.match(read('src/utils/version.js'), /1\.0\.0-release-candidate/)],
  ['Phase 11 · release constant remains release candidate before certification', () => assert.match(read('src/data/constants.js'), /1\.0\.0-release-candidate/)],
  ['Phase 11 · CI has a core validation job', () => assert.match(read('.github/workflows/ci.yml'), /core-validation:/)],
  ['Phase 11 · CI has a Chromium production job', () => assert.match(read('.github/workflows/ci.yml'), /chromium-production:/)],
  ['Phase 11 · CI has a Firefox production job', () => assert.match(read('.github/workflows/ci.yml'), /firefox-production:/)],
  ['Phase 11 · CI installs real Playwright Firefox', () => assert.match(read('.github/workflows/ci.yml'), /playwright install --with-deps firefox/)],
  ['Phase 11 · CI does not allow browser failures to continue', () => assert.doesNotMatch(read('.github/workflows/ci.yml'), /continue-on-error:\s*true/)],
  ['Phase 11 · Pages deploy follows successful CI', () => assert.match(read('.github/workflows/deploy.yml'), /workflow_run:/)],
  ['Phase 11 · Pages workflow checks CI conclusion', () => assert.match(read('.github/workflows/deploy.yml'), /workflow_run\.conclusion == 'success'/)],
  ['Phase 11 · Pages workflow uses explicit minimum permissions', () => {
    const workflow = read('.github/workflows/deploy.yml');
    for (const term of ['contents: read', 'pages: write', 'id-token: write']) assert.ok(workflow.includes(term));
  }],
  ['Phase 11 · Firefox validator prohibits Chromium substitution', () => assert.match(read('scripts/phase11-firefox-validation.mjs'), /chromiumSubstitutionUsed:\s*false/)],
  ['Phase 11 · Firefox validator records whether game code executed', () => assert.match(read('scripts/phase11-firefox-validation.mjs'), /gameCodeExecuted/)],
  ['Phase 11 · cross-browser audit compares run plans', () => assert.match(read('scripts/phase11-cross-browser-determinism.mjs'), /runPlanMatch/)],
  ['Phase 11 · cross-browser audit compares score events', () => assert.match(read('scripts/phase11-cross-browser-determinism.mjs'), /scoreEventSequenceMatch/)],
  ['Phase 11 · final audit requires real Firefox execution', () => assert.match(read('scripts/phase11-final-release-audit.mjs'), /firefoxGameCodeExecuted/)],
  ['Phase 11 · final audit requires package version 1.0.0', () => assert.match(read('scripts/phase11-final-release-audit.mjs'), /pkg\.version === '1\.0\.0'/)],
  ['Phase 11 · final packaging refuses unsigned source', () => assert.match(read('scripts/phase11-package-final.mjs'), /Final packaging refused/)],
  ['Phase 11 · candidate packaging is labeled non-final', () => assert.match(read('scripts/phase11-package-candidate.mjs'), /certification-candidate-not-final/)],
  ['Phase 11 · source manifest binds scripts and tests', () => {
    const source = read('scripts/phase11-utils.mjs');
    assert.match(source, /'src', 'tests', 'scripts', 'public', '\.github'/);
  }],
  ['Phase 11 · ZIP metrics distinguish entries and files', () => {
    const source = read('scripts/phase11-recovery.mjs');
    for (const term of ['rawEntryCount', 'regularFileCount', 'directoryEntryCount']) assert.ok(source.includes(term));
  }],
  ['Phase 11 · canonical hashes are pinned', () => {
    const source = read('scripts/phase11-utils.mjs');
    for (const name of ['GAME_DESIGN.md', 'TECHNICAL_SPEC.md', 'ART_DIRECTION.md', 'BALANCE_SPEC.md', 'QA_CHECKLIST.md']) assert.ok(source.includes(name));
  }],
  ['Phase 11 · public deployment cannot pass without evidence', () => assert.match(read('scripts/phase11-certification-status.mjs'), /unavailable-no-public-url/)],
  ['Phase 11 · no final source archive is generated by candidate packager', () => assert.doesNotMatch(read('scripts/phase11-package-candidate.mjs'), /ECHOFRAME_v1\.0\.0_final_source\.zip/)],
  ['Phase 11 · required scripts are registered', () => {
    const scripts = json('package.json').scripts;
    for (const name of ['recover:phase11', 'validate:browser:phase11', 'validate:browser:firefox:phase11', 'audit:determinism:phase11', 'audit:release:phase11']) assert.ok(scripts[name]);
  }],
  ['Phase 11 · implementation prompt is preserved in docs or input scope', () => assert.ok(existsSync(path.join(ROOT, 'docs/ECHOFRAME_PHASE10_IMPLEMENTATION_PROMPT.md')))],
];
for (const [name, fn] of contracts) test(name, fn);
