import Phaser from'phaser';import{PALETTE}from'../data/constants.js';import{TEXTURE_KEYS}from'../graphics/TextureFactory.js';import{damageAfterPierces}from'../utils/projectileDamage.js';
export class EchoProjectile extends Phaser.Physics.Arcade.Sprite{
 constructor(scene){super(scene,-1000,-1000,TEXTURE_KEYS.projectile);scene.add.existing(this);scene.physics.add.existing(this);this.setActive(false).setVisible(false);this.body.enable=false;this.hitTargets=new Map();this.resetFields();}
 activate(d){Object.assign(this,{activationId:d.activationId,ownerId:d.ownerId,sourceEventId:d.sourceEventId,remainingLifetimeMs:d.projectileLifetimeMs,damagePacket:structuredClone(d.damagePacket),faction:'echo',remainingPierce:Math.max(0,d.damagePacket?.pierceCount??0),remainingRicochets:Math.max(0,d.damagePacket?.ricochetCount??0),originalDamage:d.damagePacket?.scaledDamage??0,piercesUsed:0,ricochetsUsed:0,sameTargetGuardMs:d.damagePacket?.sameTargetGuardMs??120});this.hitTargets.clear();this.setActive(true).setVisible(true);this.body.enable=true;this.body.setCircle(d.projectileRadius,12-d.projectileRadius,6-d.projectileRadius);this.body.reset(d.x,d.y);this.setPosition(d.x,d.y).setRotation(Math.atan2(d.direction.y,d.direction.x)).setVelocity(d.direction.x*d.projectileSpeed,d.direction.y*d.projectileSpeed).setTint(d.highContrast?0xffffff:PALETTE.echoViolet).setAlpha(d.highContrast?.82:.62).setScale(.78,.6);}
 registerHit(id,nowMs=0){const last=this.hitTargets.get(id);if(last!==undefined&&nowMs-last<this.sameTargetGuardMs)return{accepted:false,continue:true};this.hitTargets.set(id,nowMs);const cont=this.remainingPierce>0;if(cont){this.remainingPierce--;this.piercesUsed++;this.damagePacket.scaledDamage=damageAfterPierces(this.originalDamage,this.piercesUsed);}return{accepted:true,continue:cont};}
 registerRicochet(decay=.82){if(this.remainingRicochets<=0)return false;this.remainingRicochets--;this.ricochetsUsed++;this.damagePacket.scaledDamage*=decay;return true;}
 updateLifetime(d){this.remainingLifetimeMs=Math.max(0,this.remainingLifetimeMs-d);return this.remainingLifetimeMs>0;}
 deactivate(r='deactivated'){if(!this.active&&!this.body.enable)return false;this.deactivationReason=r;this.setVelocity(0,0);this.body.stop();this.body.enable=false;this.setActive(false).setVisible(false).setPosition(-1000,-1000);this.clearTint().setAlpha(1).setScale(1);this.hitTargets.clear();this.resetFields();return true;}
 resetFields(){Object.assign(this,{activationId:0,ownerId:null,sourceEventId:null,remainingLifetimeMs:0,damagePacket:null,faction:null,remainingPierce:0,remainingRicochets:0,originalDamage:0,piercesUsed:0,ricochetsUsed:0,deactivationReason:'reset'});}
}
