import Phaser from'phaser';import{TEXTURE_KEYS}from'../graphics/TextureFactory.js';import{ProjectileRenderer}from'../graphics/ProjectileRenderer.js';import{damageAfterPierces}from'../utils/projectileDamage.js';
export class PlayerProjectile extends Phaser.Physics.Arcade.Sprite{
 constructor(scene){super(scene,-1000,-1000,TEXTURE_KEYS.projectile);scene.add.existing(this);scene.physics.add.existing(this);this.body.setCircle(5,7,1);this.setActive(false).setVisible(false);this.body.enable=false;this.activationId=0;this.hitTargets=new Map();}
 activate(d){Object.assign(this,{activationId:d.activationId,ownerId:d.ownerId,remainingLifetimeMs:d.lifetimeMs,damagePacket:structuredClone(d.damagePacket),remainingPierce:Math.max(0,d.damagePacket?.pierceCount??0),remainingRicochets:Math.max(0,d.damagePacket?.ricochetCount??0),originalDamage:d.damagePacket?.resolvedDamage??0,piercesUsed:0,ricochetsUsed:0,sourceEventId:d.sourceEventId??null,sameTargetGuardMs:d.damagePacket?.sameTargetGuardMs??120});this.hitTargets.clear();this.setActive(true).setVisible(true);this.body.enable=true;this.body.reset(d.x,d.y);this.setPosition(d.x,d.y).setRotation(Math.atan2(d.direction.y,d.direction.x)).setVelocity(d.direction.x*d.speed,d.direction.y*d.speed);ProjectileRenderer.configure(this,{highContrast:d.highContrast});}
 registerHit(id,nowMs=0){const last=this.hitTargets.get(id);if(last!==undefined&&nowMs-last<this.sameTargetGuardMs)return{accepted:false,continue:true};this.hitTargets.set(id,nowMs);const cont=this.remainingPierce>0;if(cont){this.remainingPierce--;this.piercesUsed++;this.damagePacket.resolvedDamage=damageAfterPierces(this.originalDamage,this.piercesUsed);}return{accepted:true,continue:cont};}
 registerRicochet(decay=.82){if(this.remainingRicochets<=0)return false;this.remainingRicochets--;this.ricochetsUsed++;this.damagePacket.resolvedDamage*=decay;return true;}
 updateLifetime(d){this.remainingLifetimeMs=Math.max(0,this.remainingLifetimeMs-d);return this.remainingLifetimeMs>0;}
 deactivate(r='deactivated'){if(!this.active&&!this.body.enable)return false;this.deactivationReason=r;this.setVelocity(0,0);this.body.stop();this.body.enable=false;this.setActive(false).setVisible(false).setPosition(-1000,-1000);this.ownerId=null;this.remainingLifetimeMs=0;this.damagePacket=null;this.remainingPierce=0;this.remainingRicochets=0;this.originalDamage=0;this.piercesUsed=0;this.ricochetsUsed=0;this.sourceEventId=null;this.hitTargets.clear();this.clearTint().setScale(1).setAlpha(1);return true;}
}
