export class EncounterTelemetry {
  constructor(initial = {}) { this.initial = { encountersCompleted: initial.encountersCompleted ?? 0, generationFallbackCount: initial.generationFallbackCount ?? 0, patternsSeen: [...(initial.encounterPatternsSeen ?? [])], threatSum: (initial.averageEncounterThreat ?? 0) * (initial.encountersCompleted ?? 0), peakEnemyCount: initial.peakActiveEnemies ?? 0, peakProjectileCount: initial.peakProjectileCount ?? 0, subordinateObjectPeak: initial.subordinateObjectPeak ?? 0, suppressionEvents: initial.suppressionEvents ?? 0, recoveryWindows: initial.recoveryWindows ?? 0 }; this.reset(); }
  reset() { this.encounters = []; this.current = null; this.generationFallbackCount = this.initial.generationFallbackCount; this.patternsSeen = new Set(this.initial.patternsSeen); this.peakEnemyCount = this.initial.peakEnemyCount; this.peakProjectileCount = this.initial.peakProjectileCount; this.subordinateObjectPeak = this.initial.subordinateObjectPeak; this.suppressionEvents = this.initial.suppressionEvents; this.recoveryWindows = this.initial.recoveryWindows; }
  begin(descriptor, context = {}) { this.current = { seed: descriptor.seed, difficulty: context.difficultyId, chamber: descriptor.chamberIndex, encounterId: descriptor.encounterId, pattern: descriptor.pattern, targetThreat: descriptor.targetThreat, actualThreat: descriptor.actualThreat, duration: 0, damageTaken: 0, playerHealthAtStart: context.playerHealth ?? 0, playerHealthAtEnd: context.playerHealth ?? 0, enemiesSpawnedByType: {}, enemiesDefeatedByType: {}, playerDamage: 0, echoDamage: 0, hostileProjectilesSpawned: 0, hostileProjectileHits: 0, echoDeployments: 0, suppressionEvents: 0, recoveryDuration: 0, peakEnemyCount: 0, peakProjectileCount: 0, completionResult: null, generationAttempts: descriptor.generationDiagnostics.generationAttempts, rejectionReasons: { ...descriptor.generationDiagnostics.rejectionReasons }, fallbackUsed: descriptor.generationDiagnostics.fallbackUsed, compositionSignature: descriptor.generationDiagnostics.compositionSignature, spawnPlanSignature: descriptor.generationDiagnostics.spawnPlanSignature }; this.patternsSeen.add(descriptor.pattern); if (this.current.fallbackUsed) this.generationFallbackCount += 1; }
  update(deltaMs, { activeEnemies = 0, activeProjectiles = 0, subordinateObjects = 0 } = {}) { if (this.current) { this.current.duration += Math.max(0, deltaMs); this.current.peakEnemyCount = Math.max(this.current.peakEnemyCount, activeEnemies); this.current.peakProjectileCount = Math.max(this.current.peakProjectileCount, activeProjectiles); } this.peakEnemyCount = Math.max(this.peakEnemyCount, activeEnemies); this.peakProjectileCount = Math.max(this.peakProjectileCount, activeProjectiles); this.subordinateObjectPeak = Math.max(this.subordinateObjectPeak, subordinateObjects); }
  recordSpawn(type) { if (this.current) this.current.enemiesSpawnedByType[type] = (this.current.enemiesSpawnedByType[type] ?? 0) + 1; }
  recordDefeat(type) { if (this.current) this.current.enemiesDefeatedByType[type] = (this.current.enemiesDefeatedByType[type] ?? 0) + 1; }
  recordSuppression() { this.suppressionEvents += 1; if (this.current) this.current.suppressionEvents += 1; }
  recordRecovery(durationMs) { this.recoveryWindows += 1; if (this.current) this.current.recoveryDuration += durationMs; }
  complete(result = 'complete', playerHealth = 0) { if (!this.current) return null; this.current.completionResult = result; this.current.playerHealthAtEnd = playerHealth; const completed = structuredClone(this.current); this.encounters.push(completed); this.current = null; return completed; }
  snapshot() { const newCompleted = this.encounters.length; const totalCompleted = this.initial.encountersCompleted + newCompleted; const threatSum = this.initial.threatSum + this.encounters.reduce((sum, entry) => sum + entry.actualThreat, 0); return { encounters: structuredClone(this.encounters), current: structuredClone(this.current), encountersCompleted: totalCompleted, patternsSeen: [...this.patternsSeen], averageThreat: totalCompleted ? threatSum / totalCompleted : 0, generationFallbackCount: this.generationFallbackCount, peakEnemyCount: this.peakEnemyCount, peakProjectileCount: this.peakProjectileCount, subordinateObjectPeak: this.subordinateObjectPeak, suppressionEvents: this.suppressionEvents, recoveryWindows: this.recoveryWindows }; }
}
