import{UpgradeApplier}from'../upgrades/UpgradeApplier.js';import{generateUpgradeOffers}from'../upgrades/UpgradeOfferGenerator.js';import{getUpgrade,INITIAL_UNLOCKED_UPGRADE_IDS,UPGRADE_IDS}from'../upgrades/UpgradeCatalog.js';import{UpgradeStatPipeline}from'../upgrades/UpgradeStatPipeline.js';import{ArcRelayBehavior}from'../upgrades/behaviors/ArcRelayBehavior.js';import{FractureRoundBehavior}from'../upgrades/behaviors/FractureRoundBehavior.js';import{ExtendedMemoryBehavior}from'../upgrades/behaviors/ExtendedMemoryBehavior.js';import{TwinRecallBehavior}from'../upgrades/behaviors/TwinRecallBehavior.js';import{ResonantDamageBehavior}from'../upgrades/behaviors/ResonantDamageBehavior.js';import{MemoryBurstBehavior}from'../upgrades/behaviors/MemoryBurstBehavior.js';import{DashWakeBehavior}from'../upgrades/behaviors/DashWakeBehavior.js';import{PhaseRecoveryBehavior}from'../upgrades/behaviors/PhaseRecoveryBehavior.js';import{KineticChargeBehavior}from'../upgrades/behaviors/KineticChargeBehavior.js';import{VectorReversalBehavior}from'../upgrades/behaviors/VectorReversalBehavior.js';import{SlipstreamBehavior}from'../upgrades/behaviors/SlipstreamBehavior.js';import{AfterburnBehavior}from'../upgrades/behaviors/AfterburnBehavior.js';import{NullAbsorptionBehavior}from'../upgrades/behaviors/NullAbsorptionBehavior.js';import{DeflectionPulseBehavior}from'../upgrades/behaviors/DeflectionPulseBehavior.js';
export class UpgradeManager{
 constructor({run,eventBus=null,unlockedIds=null,telemetry=null}={}){this.run=run;this.eventBus=eventBus;this.telemetry=telemetry;this.unlockedIds=unlockedIds??run?.unlockedUpgradeIds??INITIAL_UNLOCKED_UPGRADE_IDS;this.applier=new UpgradeApplier({eventBus});this.reactiveRemainingMs=0;this.regenDelayMs=0;this.regenTickMs=0;this.regenHealed=0;this.lastFrameAvailable=true;this.kineticBonus=0;this.arcRelay=new ArcRelayBehavior();this.fracture=new FractureRoundBehavior();this.extendedMemory=new ExtendedMemoryBehavior();this.twinRecall=new TwinRecallBehavior();this.resonantDamage=new ResonantDamageBehavior();this.memoryBurst=new MemoryBurstBehavior();this.dashWake=new DashWakeBehavior();this.phaseRecovery=new PhaseRecoveryBehavior();this.kinetic=new KineticChargeBehavior();this.vectorReversal=new VectorReversalBehavior();this.slipstream=new SlipstreamBehavior();this.afterburn=new AfterburnBehavior();this.nullAbsorption=new NullAbsorptionBehavior(run?.seed??1);this.deflection=new DeflectionPulseBehavior();}
 offers(index=0,{healthRatio=this.run?.playerHealth/Math.max(1,this.run?.playerMaximumHealth??1),unlockAll=false}={}){const unlocked=unlockAll?UPGRADE_IDS:this.unlockedIds;const o=generateUpgradeOffers({seed:this.run.seed,offerIndex:index,levels:this.run.selectedUpgrades,unlockedIds:unlocked,healthRatio});this.telemetry&&(this.telemetry.offersGenerated++,this.telemetry.offersShown++);this.eventBus?.emit('upgrade:offer:generated',{ids:o.map(x=>x.id),offerIndex:index});return o;}
 apply(id){const r=this.applier.apply(id,this.run.selectedUpgrades);if(r.applied){this.telemetry?.recordPick?.(id,r.definition.category);this.eventBus?.emit('upgrade:selected',{upgradeId:id,level:r.level});}return r;}
 level(id){return this.run.selectedUpgrades.get(id)??0;}data(id){const l=this.level(id),d=getUpgrade(id);return l&&d?d.levels[l-1]:null;}
 pipeline(){return new UpgradeStatPipeline(this.run.selectedUpgrades);}
 echoScalar(){return this.data('stable-projection')?.scalar??.55;}
 echoProfile(base={durationMs:3500,cooldownMs:8000}){const extended=this.data('extended-memory'),twin=this.data('twin-recall');const derived=this.extendedMemory.apply(base,extended);return Object.freeze({...derived,activeCap:twin?.activeCap??1,twin,phantomShieldCapacity:this.data('phantom-shield')?.capacity??0,memoryBurst:this.data('memory-burst'),dashWake:this.data('dash-wake')});}
 projectileProfile(charge=0,{consumeAfterburn=false}={}){const split=this.data('split-lens'),coil=this.data('compression-coil'),c=Math.max(0,Math.min(1,charge)),ricochet=this.data('ricochet-matrix'),afterburn=consumeAfterburn?this.afterburn.consume(this.data('afterburn')):null;if(afterburn)this.telemetry&&(this.telemetry.afterburnUses++);return{angles:(split?.angles??[0]).map(v=>v*Math.PI/180),count:split?.count??1,splitScalar:split?.scalar??1,pierce:this.data('piercing-signal')?.pierce??0,pierceDecay:this.data('piercing-signal')?.decay??.82,pierceFloor:this.data('piercing-signal')?.floor??.45,ricochet:ricochet?.bounces??0,ricochetDecay:ricochet?.decay??.82,sameTargetGuardMs:ricochet?.sameTargetGuardMs??120,speedScalar:1+(coil?(coil.speed-1)*c:0),damageScalar:1+(coil?(coil.damage-1)*c:0),arcRelay:this.data('arc-relay'),fracture:this.data('fracture-round'),afterburn};}
 fireRateScalar(){return 1+this.kineticBonus;}
 movementSpeedScalar(){const profile=this.data('slipstream');return 1+this.slipstream.bonus(profile);}
 onMovement(deltaMs,speed,maximumSpeed){this.kineticBonus=this.kinetic.update(deltaMs,speed,maximumSpeed,this.data('kinetic-charge'));this.slipstream.update(deltaMs);}
 onEchoProximity(echoId,distance){const activated=this.slipstream.pass(echoId,distance,this.data('slipstream'));if(activated)this.telemetry&&(this.telemetry.slipstreamActivations++);return activated;}
 onDashStarted(direction){this.afterburn.onDash(this.data('afterburn'));this.vectorReversal.onPrimary(direction,this.data('vector-reversal'));}
 tryVectorReversal(direction){const scalar=this.vectorReversal.trySecondary(direction,this.data('vector-reversal'));if(scalar)this.telemetry&&(this.telemetry.vectorReversals++);return scalar;}
 registerArcHit(sourceId){return this.arcRelay.registerHit(sourceId,this.data('arc-relay'));}
 createFragments(input){return this.fracture.create({...input,profile:this.data('fracture-round')});}
 memoryBurstDescriptor(echo){return this.memoryBurst.descriptor(echo,this.data('memory-burst'));}
 dashWakeDescriptor(input){return this.dashWake.descriptor({...input,profile:this.data('dash-wake')});}
 phaseRecoveryProfile(){return this.data('phase-recovery');}
 deflectionProfile(){return this.data('deflection-pulse');}
 nullAbsorptionDestroyed(projectileId){const amount=this.nullAbsorption.try(projectileId,this.data('null-absorption'));if(amount)this.telemetry&&(this.telemetry.nullAbsorptionSuccesses++);return amount;}
 onPlayerDamaged(){const r=this.data('reactive-shell');if(r)this.reactiveRemainingMs=r.durationMs;this.regenDelayMs=0;this.regenTickMs=0;}
 damageReduction(){return this.reactiveRemainingMs>0?(this.data('reactive-shell')?.reduction??0):0;}
 update(delta,health,combatActive=true,{speed=0,maximumSpeed=300}={}){this.afterburn.update(delta);this.vectorReversal.update(delta);this.nullAbsorption.update(delta);if(!combatActive)return;this.onMovement(delta,speed,maximumSpeed);this.reactiveRemainingMs=Math.max(0,this.reactiveRemainingMs-delta);const r=this.data('regenerative-circuit');if(!r)return;this.regenDelayMs+=delta;if(this.regenDelayMs<r.delayMs||this.regenHealed>=r.cap)return;this.regenTickMs+=delta;while(this.regenTickMs>=r.tickMs&&this.regenHealed<r.cap){this.regenTickMs-=r.tickMs;const healed=health.heal(1);this.regenHealed+=healed;if(!healed)break;}}
 applyChamberRepair(health){const h=this.data('emergency-repair')?.heal??0;return health.heal(h);}
 consumeLastFrame(){if(!this.lastFrameAvailable||this.level('last-frame')<1)return false;this.lastFrameAvailable=false;return true;}
 resetChamber(){this.lastFrameAvailable=true;this.reactiveRemainingMs=0;this.regenDelayMs=0;this.regenTickMs=0;this.regenHealed=0;this.kinetic.reset();this.vectorReversal.reset();this.slipstream.reset();this.afterburn.reset();this.phaseRecovery.reset();this.nullAbsorption.reset();}
 clearTransient(){this.twinRecall.clear();this.arcRelay.reset();this.resonantDamage.reset();this.resetChamber();}
 snapshot(){return{levels:Object.fromEntries(this.run.selectedUpgrades),reactiveRemainingMs:this.reactiveRemainingMs,lastFrameAvailable:this.lastFrameAvailable,kineticBonus:this.kineticBonus,slipstreamRemainingMs:this.slipstream.remainingMs,afterburnRemainingMs:this.afterburn.remainingMs,vectorReversalWindowMs:this.vectorReversal.windowMs};}}
